load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "loaderLib",
    hdrs = ["graph_loader.hpp"],
    visibility = ["//visibility:public"],
    deps = ["//src/lib/graph:graphLib"],
)
